### ISSUE TITLE
License problems

### ISSUE THREAD

**Issue by musicinmybrain** [mossblaser/aiomqtt#10]
The license field `Eclipse Public License v1.0 / Eclipse Distribution License v1.0` is unclear. It could be interpreted to mean that *both* licenses apply, or that *either* license applies.

In addition, the package should have a license file with a copyright statement and license text. Not only would this clear up confusion, but at least the Eclipse Distribution License v1.0 (effectively a BSD license) requires that `Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer`, which is not possible to comply when none of those things are present in the first place.

**Comment by mossblaser** [comment]
Thanks for pointing this out! The missing files have been added which hopefully clarify things! Please feel free to reopen if this doesn't do the trick!

**Comment by musicinmybrain** [comment]
Thanks! That, plus referencing https://www.eclipse.org/legal/eplfaq.php#DUALLIC, which clarifies:

> **For Eclipse projects which are dual-licensed, your file headers state that the code is being made available under two licenses. For example: "This program and the accompanying materials are made available under the terms of the Eclipse Public License v1.0 and Eclipse Distribution License v. 1.0 which accompanies this distribution." What is meant by the use of the conjunction "and"?**
> The code is being made available under both of the licenses. The consumer of the code can select which license terms they wish to use, modify and/or further distribute the code under.

covers everything that is needed, I think.
