### ISSUE TITLE
Add support for paho.mqtt.python 2.0+

### ISSUE THREAD

**Issue by nullr0ute** [mossblaser/aiomqtt#14]
There's breaking changes for paho.mqtt.python 2.0 and later so it would be useful to be able to use the later releases, in particular in distros.

https://github.com/eclipse/paho.mqtt.python/releases/tag/v2.0.0

**Comment by mossblaser** [comment]
Hi there,

I'm afraid this package is now deprecated and has been superseded by https://github.com/sbtinstruments/aiomqtt so I don't plan to produce any new versions.

Sorry about that!

**Comment by nullr0ute** [comment]
Not a problem, all good, useful to know in general :)
