### ISSUE TITLE
How to use encryption (tls)

### ISSUE THREAD

**Issue by elka0711** [mossblaser/aiomqtt#6]
How to use tls encryption?
(Simillar to the Paho MQTT with tls_set) 

`tls_set(ca_certs, certfile=None, keyfile=None, cert_reqs=ssl.CERT_REQUIRED,
           tls_version=ssl.PROTOCOL_TLSv1, ciphers=None)`

**Comment by mossblaser** [comment]
I'm afraid this probably isn't supported. Have you considered the better maintained https://github.com/sbtinstruments/asyncio-mqtt project? It may well have what you're looking for.
