### ISSUE TITLE
Fails to build with Python 3.10

### ISSUE THREAD

**Issue by fabaff** [mossblaser/aiomqtt#7]
```
python-aiomqtt fails to build with Python 3.10.0a2.

==================================== ERRORS
====================================
____________________ ERROR collecting tests/test_client.py
_____________________
tests/test_client.py:13: in <module>
    @pytest.fixture("module")
/usr/lib/python3.10/site-packages/_pytest/fixtures.py:1358: in fixture
    warnings.warn(FIXTURE_POSITIONAL_ARGUMENTS, stacklevel=2)
E   pytest.PytestDeprecationWarning: Passing arguments to pytest.fixture() as
positional arguments is deprecated - pass them as a keyword argument instead.
=========================== short test summary info
============================
ERROR tests/test_client.py - pytest.PytestDeprecationWarning: Passing
argumen...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection
!!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.16s
===============================
```

Origin: https://bugzilla.redhat.com/show_bug.cgi?id=1899955

**Comment by fabaff** [comment]
Any news here?

If the package is not update to work with Python 3.10 it will be removed from the Fedora Package Collection. This will have impact on all consumers of `aiomqtt`.

**Comment by mossblaser** [comment]
I'm afraid updating this and a few other related packages is still on my TODO list. I'm afraid I can't commit to updating it at any particular time but I hope to do so before the Python 3.10 release later in the year.

**Comment by fabaff** [comment]
Any progress here?

**Comment by mossblaser** [comment]
As I explained, I'm afraid its likely to be later in the year before I find time to work on this. Sorry.

**Comment by tirkarthi** [comment]
I have created a PR https://github.com/mossblaser/aiomqtt/pull/9 . It fixes pytest error and also a recent change where loop parameter being passed to several functions was removed. Feel free to review when you are free.

https://bugs.python.org/issue42392.

Thanks.
