### ISSUE TITLE
A public method to return message amount in a queue?

### ISSUE THREAD

**Issue by asaarashi** [mossblaser/aiomqtt#8]
I am building a health check API of the MQTT subscriber process for my company's monitor service, and consider taking message amount in a queue as a health metric. Is having a public method to return message amount in a queue a good idea?

Thanks for your great work!

**Comment by mossblaser** [comment]
You're right that does sound like it could be an interesting metric for some applications. Unfortunately as far as I know the [underlying mqtt library used by aiomqtt](https://github.com/eclipse/paho.mqtt.python) does not appear to make this information available. (I could be wrong, however! If so please point me to the relevant API or better yet I'd welcome a pull request :)).

**Comment by oathexodus** [comment]
Hi, @mossblaser , how about this?
```python
    def _cb_and_generator(self, *, log_context, queue_maxsize=0):
        # Queue to hold the incoming messages
        self.messages = messages = asyncio.Queue(maxsize=queue_maxsize)
```
and
```python
        async with client.filtered_messages("#") as messages:
            await client.subscribe("#")
            async for message in messages:
                print("QUEUE SIZE", client.messages.qsize())
```

**Comment by mossblaser** [comment]
I'm not sure I understand where you're proposing this might be placed?

As an aside, is there anything stoping you building this metric into your
own wrapper around the library(?)
